apiVersion: v1
kind: ConfigMap
metadata:
  name: catdog-classifier-config
  namespace: catdog-classifier
  labels:
    app: catdog-classifier
data:
  MODEL_PATH: "/app/models/model.pt"
  LOG_LEVEL: "INFO"
  WORKERS: "1"
