apiVersion: v1
kind: Service
metadata:
  name: catdog-classifier-service
  namespace: catdog-classifier
  labels:
    app: catdog-classifier
spec:
  type: NodePort
  selector:
    app: catdog-classifier
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
      nodePort: 30080
